name: Storm surge examples testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Checkout clawpack
      uses: actions/checkout@v4.1.5
      with:
        repository: clawpack/clawpack
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gfortran liblapack-pic liblapack-dev libnetcdf-dev libnetcdff-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Setup clawpack super repository
      run: |
        git submodule init
        git submodule update
        pip install --user -e .
    - name: Checkout surge-examples
      uses: actions/checkout@v4.1.5
      with:
        repository: mandli/surge-examples
    - name: Checkout branch
      run: |
        cd surge-examples
        git checkout ${{ github.ref }}
        cd ..
    - name: Lint with flake8
      run: |
        cd surge-examples
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     cd geoclaw
    #     pytest
